# Etapa 1 - Ingestão de dados

## Exercício

In [5]:
import pandas as pd

df = pd.read_csv("2004-2021.tsv", sep = "\t")

df.head(5)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [6]:
df.shape

(120823, 18)

In [7]:
df.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='object')

# Etapa 2 - Entendimento + Limpeza inicial

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 16.6+ MB

In [32]:
df.isnull().sum()

data_inicial                     0
data_final                       0
região                           0
estado                           0
produto                          0
número_de_postos_pesquisados     0
unidade_de_medida                0
preço_médio_revenda              0
desvio_padrão_revenda            0
preço_mínimo_revenda             0
preço_máximo_revenda             0
margem_média_revenda             0
coef_de_variação_revenda         0
preço_médio_distribuição         0
desvio_padrão_distribuição       0
preço_mínimo_distribuição        0
preço_máximo_distribuição        0
coef_de_variação_distribuição    0
dtype: int64

In [33]:
# Respostas:

# Existem valores nulos? Não
# Quais colunas são numéricas e quais são texto? Colunas numéricas: 5, 7, 8, 9, 10, 12; o restante das colunas está em formato "object"
# Existe coluna de data? Sim, colunas 0 e 1

In [77]:
df["data_inicial"] = pd.to_datetime(df["data_inicial"])
df["data_final"] = pd.to_datetime(df["data_final"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   data_inicial                   120823 non-null  datetime64[ns]
 1   data_final                     120823 non-null  datetime64[ns]
 2   região                         120823 non-null  object
 3   estado                         120823 non-null  object
 4   produto                        120823 non-null  object
 5   número_de_postos_pesquisados   120823 non-null  int64
 6   unidade_de_medida              120823 non-null  object
 7   preço_médio_revenda            120823 non-null  float64
 8   desvio_padrão_revenda          120823 non-null  float64
 9   preço_mínimo_revenda           120823 non-null  float64
 10  preço_máximo_revenda           120823 non-null  float64
 11  margem_média_revenda           120823 non-null  object
 12  coef_de_variação_revenda       120823 non-null  float64
 13  preço_médio_distribuição       120823 non-null  object
 14  desvio_padrão_distribuição     120823 non-null  object
 15  preço_mínimo_distribuição      120823 non-null  object
 16  preço_máximo_distribuição      120823 non-null  object
 17  coef_de_variação_distribuição  120823 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(1), object(10)
memory usage: 16.6+ MB

In [35]:
#df["PREÇO MÉDIO REVENDA"] = df["PREÇO MÉDIO REVENDA"].str.replace(",", ".").astype(float)

# o código acima não é necessário pois os valores já estão com ponto ao invés de vírgula

In [40]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.head(5)

,data_inicial,data_final,região,estado,produto,número_de_postos_pesquisados,unidade_de_medida,preço_médio_revenda,desvio_padrão_revenda,preço_mínimo_revenda,preço_máximo_revenda,margem_média_revenda,coef_de_variação_revenda,preço_médio_distribuição,desvio_padrão_distribuição,preço_mínimo_distribuição,preço_máximo_distribuição,coef_de_variação_distribuição
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

# Etapa 3 - Exploração inicial (EDA básico)

In [136]:
df["produto"] = df["produto"].str.replace("Ó", "O")

In [137]:
# Produtos pesquisados

df["produto"].unique()

array(['ETANOL HIDRATADO', 'GASOLINA COMUM', 'GLP', 'GNV', 'OLEO DIESEL',
       'OLEO DIESEL S10', 'GASOLINA ADITIVADA'], dtype=object)

In [138]:
# Quantidade de produtos pesquisados

df["produto"].nunique()

7

In [139]:
# Estados pesquisados

df["estado"].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [64]:
# Quantidade de estados pesquisados

df["estado"].nunique()

27

In [65]:
# Número de registros em cada estado

df["estado"].value_counts()

PARAIBA                4819
RIO DE JANEIRO         4819
SAO PAULO              4819
RIO GRANDE DO SUL      4819
BAHIA                  4819
SANTA CATARINA         4818
RIO GRANDE DO NORTE    4818
MINAS GERAIS           4817
ESPIRITO SANTO         4815
PERNAMBUCO             4813
CEARA                  4813
PARANA                 4807
ALAGOAS                4806
SERGIPE                4795
MATO GROSSO DO SUL     4793
MATO GROSSO            4566
AMAZONAS               4414
GOIAS                  4134
PIAUI                  4017
MARANHAO               3971
DISTRITO FEDERAL       3956
PARA                   3955
TOCANTINS              3953
RONDONIA               3950
ACRE                   3948
RORAIMA                3938
AMAPA                  3831
Name: estado, dtype: int64

In [140]:
# Preco médio geral

pmr = df.groupby("produto")["preço_médio_revenda"].mean()

print(pmr)

produto
ETANOL HIDRATADO       2.444979
GASOLINA ADITIVADA     5.049475
GASOLINA COMUM         3.195409
GLP                   47.655054
GNV                    2.033289
OLEO DIESEL            2.550975
OLEO DIESEL S10        3.269581
Name: preço_médio_revenda, dtype: float64

# Etapa 4 - Transformação (Engenharia simples)

In [91]:
# Criando coluna "ANO" a partir da data inical

df["ANO"] = df["data_inicial"].dt.year

df.head(5)

,data_inicial,data_final,região,estado,produto,número_de_postos_pesquisados,unidade_de_medida,preço_médio_revenda,desvio_padrão_revenda,preço_mínimo_revenda,preço_máximo_revenda,margem_média_revenda,coef_de_variação_revenda,preço_médio_distribuição,desvio_padrão_distribuição,preço_mínimo_distribuição,preço_máximo_distribuição,coef_de_variação_distribuição,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,2004

In [97]:
# Agrupar preco médio por ano

preco_produto_ano = df.groupby("ANO")["preço_médio_revenda"].mean()

print(preco_produto_ano)

ANO
2004     8.351370
2005     8.362085
2006     8.917147
2007     9.027187
2008     9.167603
2009     9.559809
2010    10.042510
2011    10.248218
2012    10.443419
2013     9.516663
2014    10.088056
2015    11.339927
2016    12.717348
2017    13.761745
2018    15.786378
2019    16.074283
2020    15.801747
2021    16.692066
Name: preço_médio_revenda, dtype: float64

In [98]:
# Agrupar por combustivel

preco_produto_comb = df.groupby("produto")["preço_médio_revenda"].mean()

print(preco_produto_comb)

produto
ETANOL HIDRATADO       2.444979
GASOLINA ADITIVADA     5.049475
GASOLINA COMUM         3.195409
GLP                   47.655054
GNV                    2.033289
OLEO DIESEL            3.711464
OLEO DIESEL S10        3.781366
ÓLEO DIESEL            2.422245
ÓLEO DIESEL S10        3.136145
Name: preço_médio_revenda, dtype: float64

# Insight

In [106]:
gnv = df.groupby("produto")["unidade_de_medida"].first()

print(gnv)

produto
ETANOL HIDRATADO         R$/l
GASOLINA ADITIVADA       R$/l
GASOLINA COMUM           R$/l
GLP                   R$/13Kg
GNV                     R$/m3
OLEO DIESEL              R$/l
OLEO DIESEL S10          R$/l
ÓLEO DIESEL              R$/l
ÓLEO DIESEL S10          R$/l
Name: unidade_de_medida, dtype: object

### O GLP acaba inflando o preço médio dos produtos se analisarmos toda a série pois seu preço por unidade de medida acaba sendo, em ordem de grandeza, maior do que os outros. A unidade de medidda é reais por m3, isso afeta a análise de preço, elevando a média - pode acontecer no caso do GVN também. O correto é padronizarmos todas as unidades de medida.

# Etapa 5 - Análise um pouco aprofundada

In [108]:
# Qual combustível ficou mais caro?

df.groupby(["ANO", "produto"])["preço_médio_revenda"].mean()

ANO   produto
2004  ETANOL HIDRATADO     1.528289
      GASOLINA COMUM       2.238857
      GLP                 32.258845
      GNV                  1.146280
      ÓLEO DIESEL          1.562836
                            ...
2021  GASOLINA COMUM       5.183976
      GLP                 84.920187
      GNV                  3.325968
      OLEO DIESEL          4.147167
      OLEO DIESEL S10      4.205556
Name: preço_médio_revenda, Length: 104, dtype: float64

In [110]:
# Qual estado tem combustível mais caro em média?

df.groupby("estado")["preço_médio_revenda"].mean().sort_values(ascending=False)

estado
ACRE                   14.314446
AMAPA                  14.262162
RORAIMA                13.989412
TOCANTINS              13.973487
MATO GROSSO            13.598674
RONDONIA               13.551935
PARA                   13.022828
DISTRITO FEDERAL       12.747411
MARANHAO               12.571495
PIAUI                  12.369888
GOIAS                  11.967700
MATO GROSSO DO SUL     11.492464
AMAZONAS               11.070416
CEARA                  10.863314
MINAS GERAIS           10.760187
SANTA CATARINA         10.691555
RIO GRANDE DO SUL      10.599684
SERGIPE                10.433733
RIO GRANDE DO NORTE    10.406287
PARANA                 10.394643
ALAGOAS                10.130299
ESPIRITO SANTO         10.059009
PARAIBA                10.046416
SAO PAULO              10.031501
RIO DE JANEIRO         10.018357
BAHIA                   9.898628
PERNAMBUCO              9.866559
Name: preço_médio_revenda, dtype: float64

In [111]:
# Evolução de um combustível específico (gasolina comum)

gasolina = df[df["produto"] == "GASOLINA COMUM"]

gasolina.groupby("ANO")["preço_médio_revenda"].mean()

ANO
2004    2.238857
2005    2.436973
2006    2.654691
2007    2.602651
2008    2.604931
2009    2.612350
2010    2.661623
2011    2.781453
2012    2.783480
2013    2.915976
2014    3.034759
2015    3.421235
2016    3.748847
2017    3.814546
2018    4.444822
2019    4.412135
2020    4.299953
2021    5.183976
Name: preço_médio_revenda, dtype: float64

# Validação final

In [183]:
# Evolução temporal por produto

evolucao = df.groupby(["ANO", "produto"])["preço_médio_revenda"].mean()

evolucao.loc[[2004, 2010, 2015, 2020, 2021]]

ANO   produto
2004  ETANOL HIDRATADO       1.528289
      GASOLINA COMUM         2.238857
      GLP                   32.258845
      GNV                    1.146280
      OLEO DIESEL            1.562836
2010  ETANOL HIDRATADO       1.936274
      GASOLINA COMUM         2.661623
      GLP                   38.693899
      GNV                    1.704316
      OLEO DIESEL            2.062890
2015  ETANOL HIDRATADO       2.620726
      GASOLINA COMUM         3.421235
      GLP                   50.618377
      GNV                    2.172319
      OLEO DIESEL            2.895498
      OLEO DIESEL S10        3.043467
2020  ETANOL HIDRATADO       3.460985
      GASOLINA ADITIVADA     4.625589
      GASOLINA COMUM         4.299953
      GLP                   74.278655
      GNV                    3.194975
      OLEO DIESEL            3.517985
      OLEO DIESEL S10        3.589126
2021  ETANOL HIDRATADO       4.121772
      GASOLINA ADITIVADA     5.320317
      GASOLINA COMUM         5.183976
      GLP                   84.920187
      GNV                    3.325968
      OLEO DIESEL            4.147167
      OLEO DIESEL S10        4.205556
Name: preço_médio_revenda, dtype: float64

In [176]:
# Tendência isolada (gasolina comum)

gasolina = df[df["produto"] == "GASOLINA COMUM"]

gasolina.groupby("ANO")["preço_médio_revenda"].mean()

ANO
2004    2.238857
2005    2.436973
2006    2.654691
2007    2.602651
2008    2.604931
2009    2.612350
2010    2.661623
2011    2.781453
2012    2.783480
2013    2.915976
2014    3.034759
2015    3.421235
2016    3.748847
2017    3.814546
2018    4.444822
2019    4.412135
2020    4.299953
2021    5.183976
Name: preço_médio_revenda, dtype: float64

In [164]:
# Top 5 estados mais caros

df_sem_glp = df[df["produto"] != "GLP"]

df_sem_glp.groupby("estado")["preço_médio_revenda"].mean().sort_values(ascending = False).head()

estado
ACRE        3.266313
RORAIMA     2.998435
RONDONIA    2.973948
PARA        2.970792
AMAPA       2.955231
Name: preço_médio_revenda, dtype: float64

In [167]:
df["preço_médio_revenda"].describe()

count    120823.000000
mean         11.473440
std          19.161823
min           0.766000
25%           2.157000
50%           2.899000
75%           4.026000
max         107.500000
Name: preço_médio_revenda, dtype: float64